indexes:
- kind: History
  properties:
  - name: userid
  - name: provider
  - name: created_at
    direction: desc

- kind: History
  properties:
  - name: userid
  - name: created_at
    direction: desc    